name: Beta Release Check
inputs:
  internal-dependency-prefixes:
    required: false
    description: Internal Dependency Prefix. This is used to match internal dependencies and disallow beta versions for them.    
    default: ""
runs:
  using: composite
  steps:
    - if: ${{ inputs.internal-dependency-prefixes != '' }}
      name: Create Beta Release Check Script
      run: |
        cat << 'EOF' > "${{ runner.temp }}/beta-check.sh"
        set -e
        delimited_prefixes=$(sed 's/ *, */|/g' <<< $1)
        if egrep "($delimited_prefixes).*\-beta\-" package.json; then
          echo "ERROR: should not consume a beta version of an internal dependency. Make sure to revert/update to use a proper release."
          exit 1
        fi
        EOF
        chmod +x ${{ runner.temp }}/beta-check.sh
      shell: bash
    - if: ${{ inputs.internal-dependency-prefixes != '' }}
      name: Run Beta Release Check
      run: bash ${{ runner.temp }}/beta-check.sh ${{ inputs.internal-dependency-prefixes }}
      shell: bash