name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  beta-dependencies-check:
    - name: Beta Dependencies Check
      runs-on: [self-hosted, general-ubuntu]
      run: ./beta-check.sh
      shell: bash