name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  beta-dependencies-check:
    - name: Beta Dependencies Check
      runs-on: [self-hosted, general-ubuntu]
      run: ./beta-check.sh ../**/*/package.json
      shell: bash
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
