name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: [self-hosted, general-ubuntu]
    steps:
      - name: Checkout
        run: echo "${{ $GITHUB_REF_NAME }}"
