name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  beta-dependencies-check:
    runs-on: ubuntu-latest
    steps:
      - name: Beta Dependencies Check
        run: ./.github/workflows/beta-check.sh ./package.json

        shell: bash