name: Get Latest Commit Message

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  get-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if remote branch exists
        id: check-branch
        run: |
          git ls-remote --exit-code --heads origin ${{ github.event.inputs.branch }}
          echo "::set-output name=branch_exists::true"
        continue-on-error: true  # Continue even if the branch doesn't exist
      - name: Get latest commit message
        if: steps.check-branch.outputs.branch_exists == 'true'
        id: latest-commit
        run: |
          git fetch origin ${{ github.event.inputs.branch }}
          latest_commit_message=$(git log -1 --pretty=%B origin/${{ github.event.inputs.branch }})
          echo "::set-output name=commit_message::$latest_commit_message"

      - name: Print latest commit message
        run: echo "Latest commit message ${{ steps.latest-commit.outputs.commit_message }}"
