name: Get Latest Commit Message

on:
  pull_request:

jobs:
  get-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compare
        run: echo ${{ github.ref }} ${{ github.head_ref }}
    
      
