name: Sandbox

on:
  pull_request:
  workflow_dispatch:

jobs:
  html-file:
    name: HTML File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integrate translations from main branch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: integrate-translations-master
          client-payload: |
            {
              "file": "${{ github.workspace }}/file.txt"
            }
