name: Get Latest Commit Message

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  get-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit message
        id: latest-commit
        run: |
          git fetch origin ${{ github.event.inputs.branch }}
          latest_commit_message=$(git log -1 --pretty=%B origin/${{ github.event.inputs.branch }})
          echo "::set-output name=commit_message::$latest_commit_message"

      - name: Print latest commit message
        run: echo "Latest commit message ${{ steps.latest-commit.outputs.commit_message }}"
