name: Get Latest Commit Message

on:
  workflow_dispatch:

jobs:
  get-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom action
        uses: OmarJaroudi/get-latest-commit@bootstrap-pr
        with: 
          branch-name: testbranch
      
