name: Get Latest Commit Message

on:
  workflow_dispatch:

jobs:
  get-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom action
        id: latest-commit
        uses: OmarJaroudi/get-latest-commit@v1
        with: 
          branch-name: testbranch

      - name: Print commit info
        run: |
         echo "Commit sha ${{ steps.latest-commit.outputs.sha }}"
         echo "Commit author ${{ steps.latest-commit.outputs.author }}"
         echo "Commit message ${{ steps.latest-commit.outputs.message }}"

    
      
