name: Get Latest Commit Message

on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for .pre-commit-config file
        id: check_pre_commit_config
        uses: andstor/file-existence-action@v2
        with:
          files: ".pre-commit-config.yaml, .pre-commit-config.yml"
      - name: Pre-commit
        if: steps.check_pre_commit_config.outputs.files_exists == 'true'
        run: echo "Found file"
    
      
