name: Sandbox

on:
  workflow_dispatch:

jobs:
  html-file:
    name: HTML File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comment bundle stats report link
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## Bundle Stats Report
            Below is a bundle stats report for this PR

            ---
            <!-- bundle stats report -->
            Link to HTML page: [File.html](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/locales/file.html)
