name: Get Latest Commit Message

on:
  workflow_dispatch:

jobs:
  get-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compare
        if: >
          '2' == '2'
          && '1' != '1'
        run: echo 'here'
    
      
