name: Sandbox

on:
  pull_request:
  workflow_dispatch:

jobs:
  html-file:
    name: HTML File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Sanitize head branch name
        id: branch
        uses: transferwise/sanitize-branch-name@v1
      - run: echo ${{ steps.branch.outputs.sanitized-branch-name }}
