name: CI

on:
  workflow_dispatch:
  push:

jobs:
  translations-push:
    env:
    name: Upload translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sanitize branch name
        id: branch
        uses: transferwise/sanitize-branch-name@v1
      - name: Set Crowdin branch name
        id: crowdin-branch
        run: |
          echo "name=${{ steps.branch.outputs.sanitized-branch-name }}" >> "$GITHUB_OUTPUT"
      - name: Push translations to Crowdin
        uses: crowdin/github-action@v1
        with:
          crowdin_branch_name: ${{ steps.crowdin-branch.outputs.name }}
          push_translations: false
          upload_sources: true
          upload_translations: true
          upload_translations_args: "--translate-hidden"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: 595315
          CROWDIN_PERSONAL_TOKEN: a31f27bdaa71a0c3951b4e243c0666f217841051ffbb325535180cfd7f7fc7f19c570c21ce29117b
