name: Translations - Status

on:
  workflow_dispatch:

jobs:
  translations-integrate:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CROWDIN_PROJECT_ID: 595315
      CROWDIN_PERSONAL_TOKEN: a31f27bdaa71a0c3951b4e243c0666f217841051ffbb325535180cfd7f7fc7f19c570c21ce29117b
    name: Report translations progress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Crowdin CLI
        run: npm i -g @crowdin/cli
      - run: crowdin -V
