name: Translations - Integrate

on:
  workflow_dispatch:
  repository_dispatch:
    types: [integrate-translations-master]

jobs:
  translations-integrate:
    name: Integrate translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print file content
        run: |
          echo "The file content:"
          cat ${{ github.event.client_payload.file }}